server:
  port: 8081

spring:
  application:
    name: department-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost # Or 127.0.0.1, or your machine's hostname/IP
        preferIpAddress: true # Optional, but often useful

